# Compile the actual generated kernels without requiring an OpenCL runtime or GPU.
# This catches compiler/type errors; it does not verify GPU hashes or performance.
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
foreach(period IN ITEMS 1 1205100 4294967297)
    if(period EQUAL 1)
        set(epoch 0)
    else()
        set(epoch 650)
    endif()
    foreach(group IN ITEMS 64 128 256)
        foreach(mode IN ITEMS legacy inline legacy-subgroup inline-subgroup legacy-shuffle inline-shuffle)
            if(mode MATCHES "(subgroup|shuffle)$")
                set(standard CL2.0)
            else()
                set(standard CL1.2)
            endif()
            set(source "${OUTPUT_DIR}/kernel-${period}-${group}-${mode}.cl")
            execute_process(COMMAND "${GENERATOR}" "${period}" "${epoch}" "${group}" "${mode}"
                "${KERNEL_SOURCE}" OUTPUT_FILE "${source}" RESULT_VARIABLE result)
            if(NOT result STREQUAL "0")
                message(FATAL_ERROR "OpenCL kernel generation failed: ${source}")
            endif()
            # SPIR exposes the optional OpenCL subgroup declarations on older Clang versions.
            execute_process(COMMAND "${CLANG}" --target=spir64 -x cl "-cl-std=${standard}" -fgnu89-inline
                -Werror=incompatible-pointer-types -O2 -S -emit-llvm "${source}" -o "${source}.ll"
                RESULT_VARIABLE result ERROR_VARIABLE errors)
            if(NOT result STREQUAL "0")
                message(FATAL_ERROR "OpenCL kernel compilation failed: ${source}\n${errors}")
            endif()
            if(mode MATCHES "shuffle$")
                file(READ "${source}.ll" ir)
                if(NOT ir MATCHES "call[^\n]*sub_group_shuffle")
                    message(FATAL_ERROR "OpenCL shuffle path was not compiled: ${source}")
                endif()
            endif()
        endforeach()
    endforeach()
endforeach()
message(STATUS "Compiled 54 OpenCL kernels (legacy/inline mix, portable/subgroup broadcasts and shuffles); GPU execution was not tested")
