set(SOURCES
	Farm.cpp Farm.h
	Miner.h Miner.cpp
)

include_directories(BEFORE ..)

add_library(ethcore ${SOURCES})
target_link_libraries(ethcore PUBLIC devcore crypto JsonCpp::JsonCpp PRIVATE hwmon Boost::filesystem Boost::process)

if(ETHASHCL)
	target_link_libraries(ethcore PUBLIC ethash-cl)
endif()
if(ETHASHCUDA)
	target_link_libraries(ethcore PUBLIC ethash-cuda)
endif()
if(ETHASHCPU)
	target_link_libraries(ethcore PUBLIC ethash-cpu)
endif()
